name:                MinDepthSN
version:             0.1.0.0
git:                 "https://gitlab.informatik.uni-bremen.de/haslop/min-depth-sn"
license:             BSD3
author:              "Tobias Haslop"
maintainer:          "haslop@uni-bremen.de"
copyright:           "2018 Tobias Haslop"
tested-with:         "GHC == 8.10.1"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
#description:         Please see the README on GitHub at <https://gitlab.informatik.uni-bremen.de/haslop/min-depth-sn#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Werror
- -Wmissing-deriving-strategies
# - -fno-warn-orphans
# - -fno-warn-incomplete-patterns
- -fno-warn-unused-top-binds
- -fno-warn-unused-imports
- -O2
- -fno-ignore-asserts
# - -fignore-asserts

library:
  source-dirs: src

  dependencies:
  - ipasir
  - containers
  - array
  - finite-typelits
  - generic-data
  - optics-core


executables:
  MinDepthSN-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - MinDepthSN
    - containers

tests:
  MinDepthSN-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - MinDepthSN
    - tasty
    - tasty-hunit
    - tasty-smallcheck
    - HUnit
    - smallcheck
    - finite-typelits
