name:                MinDepthSN
version:             0.1.0.0
github:              "githubuser/MinDepthSN"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MinDepthSN#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - ipasir
  - containers
  - transformers
  - split
  - enumerate
  - array
  - finite-typelits
  - ghc-typelits-natnormalise
  - ghc-typelits-knownnat
  #- profunctors
  #- lens

executables:
  MinDepthSN-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -fwarn-incomplete-patterns
    - -fwarn-unused-matches
    - -fno-warn-orphans
    - -Werror
    - -O2
    dependencies:
    - MinDepthSN

tests:
  MinDepthSN-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - MinDepthSN
