resolver: lts-12.10

packages:
- .
- ./ipasir
# - location: 
#     git: https://github.com/reinerp/indexed-extras.git
#     commit: 8b38e7503c030644154e844cd932003d9438cfa2
#   extra-dep: true

extra-deps:
- enumerate-0.2.2
- spiros-0.0.0
# - indexed-0.1.3
# fix is not yet on hackage/stackage: https://github.com/reinerp/indexed-extras/pull/8
# - git: https://github.com/reinerp/indexed-extras.git 
#   commit: 8b38e7503c030644154e844cd932003d9438cfa2
- base-orphans-0.8@sha256:4885caa82ab94fa5cb841d6d06a43a97cdc7e835f346be4f11c1cc5707b886db
- generic-data-0.3.0.0
