name: ipasir
version: 0.1.0.0
author: "Tobias Haslop"
maintainer: "haslop@uni-bremen.de"
copyright: "2017 Philipp Dargel, 2018- Tobias Haslop"
license: MIT
ghc-options:
- -static
- -optl-static
- -O2
- -Wall
- -Werror
- -Wmissing-deriving-strategies 
include-dirs:
- c-sources
build-tools:
- c2hs
dependencies:
- base >= 4.7 && < 5
- transformers
- primitive
# - indexed-extras
library:
  source-dirs: src
  extra-libraries: 
  - ipasircryptominisat5
  extra-lib-dirs:
  - C:/PROGRA~2/cryptominisat5/lib

  # extra-libraries: 
  # - jamsats
  # - stdc++ # for static solver libs this line is most likely needed too
  # extra-lib-dirs:
  # - C:/Users/Tobias/Documents/Uni/ba/JamSAT-install/lib