name: ipasir
version: '0.1.0.0'
author: Author name here
maintainer: example@example.com
copyright: 2017 Author name here
license: MIT
ghc-options:
- -static
- -optl-static
- -O2
- -Wall
- -Werror
include-dirs:
- c-sources
build-tools:
- c2hs
dependencies:
- base >= 4.7 && < 5
- transformers
# - indexed-extras
library:
  source-dirs: src
  extra-libraries: 
  - ipasircryptominisat5
  extra-lib-dirs:
  - C:/PROGRA~1/cryptominisat5/lib
  include-dirs:
  - C:/PROGRA~1/cryptominisat5/include