resolver: lts-12.2

packages:
- '.'
# - location: # fix is not yet on hackage/stackage: https://github.com/reinerp/indexed-extras/pull/8
#     git: https://github.com/reinerp/indexed-extras.git
#     commit: 8b38e7503c030644154e844cd932003d9438cfa2
#   extra-dep: true

extra-deps:
#- indexed-0.1.3